image: vasyakrg/docker:latest

stages:
  - build
  - test
  - review
  - stage
  - production

# variables:
#   DATABASE_URL: 'mongodb://mongo/user_posts'

# before_script:
#   - docker login -u $REGISTRY_USER -p $REGISTRY_PASSWORD docker.io
  # - apk add --no-cache py-pip python-dev libffi-dev openssl-dev gcc libc-dev make
  # - pip install docker-compose
  # - docker info

build_job:
  stage: build
  before_script:
    - echo $REGISTRY_PASSWORD | docker login -u $REGISTRY_USER --password-stdin docker.io
  script:
    - echo 'Building'
    - docker build -t vasyakrg/reddit:$CI_JOB_ID .
    - docker push vasyakrg/reddit:$CI_JOB_ID

test_unit_job:
  stage: test
  script:
    - echo 'Testing 1'

test_unit_job:
  stage: test
  # services:
  #   - mongo:latest
  script:
    # - ruby simpletest.rb
    - echo 'Testing 2'

test_integration_job:
  stage: test
  script:
    - echo 'Testing 2'

deploy_dev_job:
  stage: review
  before_script:
    - apk update
    - apk add openssh-client
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - echo 'Deploy'
    - scp docker-compose.yml appuser@docker1.aits.life:$HOME
    - ssh appuser@docker1.aits.life "export CI_JOB_ID=$CI_JOB_ID"
    - ssh appuser@docker1.aits.life "sudo docker-compose down && docker-compose up -d"
  environment:
    name: dev
    url: http://docker1.aits.life:9292
  tags:
    - ubuntu

branch review:
 stage: review
 script: echo "Deploy to $CI_ENVIRONMENT_SLUG"
 environment:
   name: branch/$CI_COMMIT_REF_NAME
   url: http://$CI_ENVIRONMENT_SLUG.example.com
 only:
   - branches
 except:
   - master

staging:
  stage: stage
  when: manual
  only:
    - /^\d+\.\d+\.\d+/
  script:
    - echo 'Deploy'
  environment:
    name: stage
    url: https://beta.example.com

production:
  stage: production
  when: manual
  only:
    - /^\d+\.\d+\.\d+/
  script:
    - echo 'Deploy'
  environment:
    name: production
    url: https://example.com
