image: vasyakrg/docker:latest

stages:
  - build
  - test
  - review
  - stage
  - production

# variables:
#   DATABASE_URL: 'mongodb://mongo/user_posts'

before_script:
  - apk update
  - apk add openssh-client
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

build_job:
  stage: build
  before_script:
    - echo $REGISTRY_PASSWORD | docker login -u $REGISTRY_USER --password-stdin docker.io
  script:
    - echo 'Building'
    - docker build -t vasyakrg/reddit:$CI_JOB_ID .
    - docker tag vasyakrg/reddit:$CI_JOB_ID vasyakrg/reddit:latest
    - docker push vasyakrg/reddit:$CI_JOB_ID
    - docker push vasyakrg/reddit:latest

test_unit_job:
  stage: test
  script:
    - echo 'Testing 1'

test_unit_job:
  stage: test
  script:
    # - ruby simpletest.rb
    - echo 'Testing 2'
    - docker run -it -rm -p 9292:9292 vasyakrg/reddit:latest
    # - scp docker-compose.yml appuser@docker-test1.aits.life:/home/appuser
    # - ssh appuser@docker-test1.aits.life "sudo docker-compose up -d"
    # - ssh appuser@docker-test1.aits.life "sudo docker exec -it vasyakrg_microservices_reddit_1 bash -c 'cd reddit/ && ruby simpletest.rb'"
    # - ssh appuser@docker-test1.aits.life "sudo docker-compose down"

test_integration_job:
  stage: test
  script:
    - echo 'Testing 2'

deploy_dev_job:
  stage: review
  before_script:
    - gitlab-ci/apk-ssh.sh
  script:
    - echo 'Deploy'
    - scp docker-compose.yml appuser@docker1.aits.life:/home/appuser
    - ssh appuser@docker1.aits.life "sudo docker-compose down && sudo docker-compose up -d"
  environment:
    name: dev
    url: http://docker1.aits.life:9292
  tags:
    - ubuntu

branch review:
 stage: review
 script: echo "Deploy to $CI_ENVIRONMENT_SLUG"
 environment:
   name: branch/$CI_COMMIT_REF_NAME
   url: http://$CI_ENVIRONMENT_SLUG.example.com
 only:
   - branches
 except:
   - master

staging:
  stage: stage
  when: manual
  only:
    - /^\d+\.\d+\.\d+/
  script:
    - echo 'Deploy'
  environment:
    name: stage
    url: https://beta.example.com

production:
  stage: production
  when: manual
  only:
    - /^\d+\.\d+\.\d+/
  script:
    - echo 'Deploy'
  environment:
    name: production
    url: https://example.com
